### ISSUE TITLE
const fn new

### ISSUE THREAD

**Issue by ryanolf** [carlomilanesi/rs-measures#2]
## Problem

I want to define `static` or `const` quantities with units.

## Solution
Can the `new` function in the `Measure` and `MeasurePoint` be const? Also, if any of the arithmetic and conversion ops can be const, that’s handy too.

**Comment by carlomilanesi** [comment]
The arithmetic operations and the conversions cannot be trivially made `const`, because they use traits functions, and traits do not support `const` functions.
I have just pushed a commit with this comment:

### Setting `const` functions whenever possible

The following functions have become `const fn`:
* For type `Measure`: `new`.
* For type `MeasurePoint`: `new`.
* For type `UnsignedDirection`: `to_measure_point`.
* For type `SignedDirection`: `to_measure_point`.
* For type `Measure2d`: `new`, `x`, `y`.
* For type `MeasurePoint2d`: `new`, `x`, `y`.
* For type `LinearMap2d`: `new`.
* For type `AffineMap2d`: `new`.
* For type `Measure3d`: `new`, `x`, `y`, `z`.
* For type `MeasurePoint3d`: `new`, `x`, `y`, `z`.
* For type `LinearMap3d`: `new`
* For type `AffineMap3d`: `new`

**Comment by ryanolf** [comment]
Thanks @carlomilanesi
